name: peppolsnap
description: Open-source PEPPOL invoice creator for Belgian plumbers & freelancers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  shared_preferences: ^2.2.3
  intl: ^0.20.2

  # Camera & OCR
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^12.0.1

  # Network & file
  http: ^1.2.2
  path_provider: ^2.1.4
  open_file: ^3.5.7

  # Optional nice-to-have
  flutter_launcher_icons: ^0.14.4   # for custom app icon later
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Uncomment and add your logo here later
  # assets:
  #   - assets/logo.png
